version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:0.8.2-pg16
    container_name: finance-postgres
    restart: always
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - finance_pg:/var/lib/postgresql/data

  backend:
    build: .
    container_name: finance-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finance_db
      SPRING_DATASOURCE_USERNAME: finance_user
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    build: ./frontend
    container_name: finance-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  finance_pg: