CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE app_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(160) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(60)  NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_app_user_email
        CHECK (BTRIM(email) <> ''),

    CONSTRAINT ck_app_user_display_name
        CHECK (BTRIM(display_name) <> ''),

    CONSTRAINT ck_app_user_role
        CHECK (role IN ('USER', 'ADMIN'))
);

CREATE UNIQUE INDEX uk_app_user_email_lower
    ON app_user (LOWER(email));


CREATE TABLE user_preference
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT         NOT NULL UNIQUE,
    region_code            VARCHAR(32)    NOT NULL DEFAULT 'CN',
    region_name            VARCHAR(80)    NOT NULL DEFAULT '全国',
    price_index            NUMERIC(5, 2)  NOT NULL DEFAULT 1.00,
    spending_level         VARCHAR(20)    NOT NULL DEFAULT 'STANDARD',
    monthly_income         NUMERIC(14, 2),
    default_monthly_budget NUMERIC(14, 2),
    warning_enabled        BOOLEAN        NOT NULL DEFAULT TRUE,
    warning_level          VARCHAR(20)    NOT NULL DEFAULT 'MEDIUM',
    preferred_language     VARCHAR(10)    NOT NULL DEFAULT 'zh-CN',
    speech_language        VARCHAR(10)    NOT NULL DEFAULT 'zh-CN',
    currency               VARCHAR(3)     NOT NULL DEFAULT 'CNY',
    created_at             TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_preference_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT ck_user_preference_price_index
        CHECK (price_index BETWEEN 0.10 AND 10.00),

    CONSTRAINT ck_user_preference_spending_level
        CHECK (
            spending_level IN (
                               'ECONOMICAL',
                               'STANDARD',
                               'COMFORTABLE',
                               'PREMIUM',
                               'CUSTOM'
                )
            ),

    CONSTRAINT ck_user_preference_income
        CHECK (monthly_income IS NULL OR monthly_income >= 0),

    CONSTRAINT ck_user_preference_budget
        CHECK (
            default_monthly_budget IS NULL
                OR default_monthly_budget >= 0
            ),

    CONSTRAINT ck_user_preference_warning_level
        CHECK (warning_level IN ('LOW', 'MEDIUM', 'HIGH')),

    CONSTRAINT ck_user_preference_language
        CHECK (preferred_language IN ('zh-CN', 'en-US')),

    CONSTRAINT ck_user_preference_speech_language
        CHECK (speech_language IN ('zh-CN', 'en-US')),

    CONSTRAINT ck_user_preference_currency
        CHECK (currency ~ '^[A-Z]{3}$')
    );


CREATE TABLE category
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(50) NOT NULL UNIQUE,
    name_zh        VARCHAR(50) NOT NULL,
    name_en        VARCHAR(50) NOT NULL,
    parent_id      BIGINT,
    icon           VARCHAR(50),
    sort_order     INTEGER     NOT NULL DEFAULT 0,
    system_defined BOOLEAN     NOT NULL DEFAULT TRUE,
    active         BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_category_parent
        FOREIGN KEY (parent_id)
            REFERENCES category (id)
            ON DELETE RESTRICT,

    CONSTRAINT ck_category_code
        CHECK (BTRIM(code) <> ''),

    CONSTRAINT ck_category_name_zh
        CHECK (BTRIM(name_zh) <> ''),

    CONSTRAINT ck_category_name_en
        CHECK (BTRIM(name_en) <> '')
);


CREATE TABLE record_batch
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL,
    source          VARCHAR(20) NOT NULL,
    input_language  VARCHAR(10) NOT NULL DEFAULT 'zh-CN',
    original_text   TEXT,
    normalized_text TEXT,
    extracted_data  JSONB,
    item_count      INTEGER     NOT NULL DEFAULT 0,
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    error_message   VARCHAR(500),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at    TIMESTAMPTZ,

    CONSTRAINT fk_record_batch_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT ck_record_batch_source
        CHECK (
            source IN (
                       'MANUAL',
                       'TEXT',
                       'VOICE',
                       'AI',
                       'IMPORT'
                )
            ),

    CONSTRAINT ck_record_batch_language
        CHECK (input_language IN ('zh-CN', 'en-US')),

    CONSTRAINT ck_record_batch_count
        CHECK (item_count >= 0),

    CONSTRAINT ck_record_batch_status
        CHECK (
            status IN (
                       'DRAFT',
                       'READY',
                       'CONFIRMED',
                       'FAILED'
                )
            )
);


CREATE TABLE expense_record
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT         NOT NULL,
    category_id       BIGINT         NOT NULL,
    batch_id          BIGINT,
    item_name         VARCHAR(120)   NOT NULL,
    merchant          VARCHAR(120),
    amount            NUMERIC(14, 2) NOT NULL,
    currency          VARCHAR(3)     NOT NULL DEFAULT 'CNY',
    quantity          NUMERIC(10, 2),
    unit              VARCHAR(30),
    occurred_at       TIMESTAMPTZ    NOT NULL,
    note              VARCHAR(500),
    source            VARCHAR(20)    NOT NULL,
    raw_text          TEXT,
    ai_confidence     NUMERIC(5, 4),
    anomaly_level     VARCHAR(20)    NOT NULL DEFAULT 'NONE',
    anomaly_score     NUMERIC(5, 4),
    anomaly_message   VARCHAR(500),
    anomaly_confirmed BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_expense_record_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_expense_record_category
        FOREIGN KEY (category_id)
            REFERENCES category (id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_expense_record_batch
        FOREIGN KEY (batch_id)
            REFERENCES record_batch (id)
            ON DELETE SET NULL,

    CONSTRAINT ck_expense_record_item_name
        CHECK (BTRIM(item_name) <> ''),

    CONSTRAINT ck_expense_record_amount
        CHECK (amount > 0 AND amount <= 99999999.99),

    CONSTRAINT ck_expense_record_currency
        CHECK (currency ~ '^[A-Z]{3}$'),

    CONSTRAINT ck_expense_record_quantity
        CHECK (quantity IS NULL OR quantity > 0),

    CONSTRAINT ck_expense_record_source
        CHECK (
            source IN (
                'MANUAL',
                'TEXT',
                'VOICE',
                'AI',
                'IMPORT'
            )
        ),

    CONSTRAINT ck_expense_record_confidence
        CHECK (
            ai_confidence IS NULL
            OR ai_confidence BETWEEN 0 AND 1
        ),

    CONSTRAINT ck_expense_record_anomaly_level
        CHECK (
            anomaly_level IN (
                'NONE',
                'NOTICE',
                'WARNING'
            )
        ),

    CONSTRAINT ck_expense_record_anomaly_score
        CHECK (
            anomaly_score IS NULL
            OR anomaly_score BETWEEN 0 AND 1
        )
);


CREATE TABLE budget_plan
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL,
    category_id  BIGINT,
    budget_month DATE           NOT NULL,
    limit_amount NUMERIC(14, 2) NOT NULL,
    alert_ratio  NUMERIC(5, 4)  NOT NULL DEFAULT 0.8000,
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_budget_plan_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_budget_plan_category
        FOREIGN KEY (category_id)
            REFERENCES category (id)
            ON DELETE RESTRICT,

    CONSTRAINT ck_budget_plan_month
        CHECK (EXTRACT(DAY FROM budget_month) = 1),

    CONSTRAINT ck_budget_plan_amount
        CHECK (limit_amount > 0),

    CONSTRAINT ck_budget_plan_alert
        CHECK (alert_ratio > 0 AND alert_ratio <= 1)
);

CREATE UNIQUE INDEX uk_budget_plan_scope
    ON budget_plan (
                    user_id,
                    budget_month,
                    COALESCE(category_id, 0)
        );


CREATE TABLE price_reference_rule
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalized_keyword VARCHAR(120)   NOT NULL,
    aliases            JSONB          NOT NULL DEFAULT '[]'::JSONB,
    category_id        BIGINT,
    region_code        VARCHAR(32),
    spending_level     VARCHAR(20),
    unit               VARCHAR(30),
    min_reasonable     NUMERIC(14, 2),
    max_reasonable     NUMERIC(14, 2) NOT NULL,
    severity           VARCHAR(20)    NOT NULL DEFAULT 'WARNING',
    enabled            BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_price_rule_category
        FOREIGN KEY (category_id)
            REFERENCES category (id)
            ON DELETE RESTRICT,

    CONSTRAINT ck_price_rule_keyword
        CHECK (BTRIM(normalized_keyword) <> ''),

    CONSTRAINT ck_price_rule_spending_level
        CHECK (
            spending_level IS NULL
                OR spending_level IN (
                                      'ECONOMICAL',
                                      'STANDARD',
                                      'COMFORTABLE',
                                      'PREMIUM',
                                      'CUSTOM'
                )
            ),

    CONSTRAINT ck_price_rule_min
        CHECK (min_reasonable IS NULL OR min_reasonable >= 0),

    CONSTRAINT ck_price_rule_max
        CHECK (max_reasonable > 0),

    CONSTRAINT ck_price_rule_range
        CHECK (
            min_reasonable IS NULL
                OR max_reasonable >= min_reasonable
            ),

    CONSTRAINT ck_price_rule_severity
        CHECK (severity IN ('NOTICE', 'WARNING'))
);


CREATE TABLE monthly_prediction
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT         NOT NULL,
    target_month     DATE           NOT NULL,
    predicted_amount NUMERIC(14, 2) NOT NULL,
    lower_bound      NUMERIC(14, 2),
    upper_bound      NUMERIC(14, 2),
    algorithm        VARCHAR(80)    NOT NULL,
    model_version    VARCHAR(30)    NOT NULL,
    based_on_months  INTEGER        NOT NULL,
    explanation      TEXT,
    generated_at     TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_monthly_prediction_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT uk_monthly_prediction
        UNIQUE (user_id, target_month, model_version),

    CONSTRAINT ck_monthly_prediction_month
        CHECK (EXTRACT(DAY FROM target_month) = 1),

    CONSTRAINT ck_monthly_prediction_amount
        CHECK (predicted_amount >= 0),

    CONSTRAINT ck_monthly_prediction_lower
        CHECK (lower_bound IS NULL OR lower_bound >= 0),

    CONSTRAINT ck_monthly_prediction_upper
        CHECK (upper_bound IS NULL OR upper_bound >= 0),

    CONSTRAINT ck_monthly_prediction_range
        CHECK (
            lower_bound IS NULL
                OR upper_bound IS NULL
                OR upper_bound >= lower_bound
            ),

    CONSTRAINT ck_monthly_prediction_algorithm
        CHECK (
            algorithm IN (
                          'WEIGHTED_MOVING_AVERAGE',
                          'TREND_ADJUSTED_AVERAGE',
                          'INSUFFICIENT_DATA_ESTIMATE'
                )
            ),

    CONSTRAINT ck_monthly_prediction_month_count
        CHECK (based_on_months >= 0)
);


CREATE TABLE financial_health_score
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL,
    score_month     DATE          NOT NULL,
    total_score     NUMERIC(5, 2) NOT NULL,
    budget_score    NUMERIC(5, 2) NOT NULL,
    stability_score NUMERIC(5, 2) NOT NULL,
    saving_score    NUMERIC(5, 2) NOT NULL,
    structure_score NUMERIC(5, 2) NOT NULL,
    risk_score      NUMERIC(5, 2) NOT NULL,
    level           VARCHAR(20)   NOT NULL,
    detail          JSONB         NOT NULL DEFAULT '{}'::JSONB,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_health_score_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT uk_health_score_user_month
        UNIQUE (user_id, score_month),

    CONSTRAINT ck_health_score_month
        CHECK (EXTRACT(DAY FROM score_month) = 1),

    CONSTRAINT ck_health_total
        CHECK (total_score BETWEEN 0 AND 100),

    CONSTRAINT ck_health_budget
        CHECK (budget_score BETWEEN 0 AND 30),

    CONSTRAINT ck_health_stability
        CHECK (stability_score BETWEEN 0 AND 20),

    CONSTRAINT ck_health_saving
        CHECK (saving_score BETWEEN 0 AND 20),

    CONSTRAINT ck_health_structure
        CHECK (structure_score BETWEEN 0 AND 15),

    CONSTRAINT ck_health_risk
        CHECK (risk_score BETWEEN 0 AND 15),

    CONSTRAINT ck_health_level
        CHECK (
            level IN (
                      'EXCELLENT',
                      'GOOD',
                      'FAIR',
                      'RISK'
                )
            )
);


CREATE TABLE saving_advice
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT         NOT NULL,
    health_score_id  BIGINT,
    target_month     DATE           NOT NULL,
    title            VARCHAR(150)   NOT NULL,
    content_markdown TEXT           NOT NULL,
    expected_saving  NUMERIC(14, 2),
    priority         VARCHAR(20)    NOT NULL DEFAULT 'MEDIUM',
    status           VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE',
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_saving_advice_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_saving_advice_health
        FOREIGN KEY (health_score_id)
            REFERENCES financial_health_score (id)
            ON DELETE SET NULL,

    CONSTRAINT ck_saving_advice_month
        CHECK (EXTRACT(DAY FROM target_month) = 1),

    CONSTRAINT ck_saving_advice_title
        CHECK (BTRIM(title) <> ''),

    CONSTRAINT ck_saving_advice_content
        CHECK (BTRIM(content_markdown) <> ''),

    CONSTRAINT ck_saving_advice_amount
        CHECK (expected_saving IS NULL OR expected_saving >= 0),

    CONSTRAINT ck_saving_advice_priority
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),

    CONSTRAINT ck_saving_advice_status
        CHECK (
            status IN (
                       'ACTIVE',
                       'ADOPTED',
                       'DISMISSED'
                )
            )
);


CREATE TABLE ai_conversation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    title      VARCHAR(150) NOT NULL,
    status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_ai_conversation_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT ck_ai_conversation_title
        CHECK (BTRIM(title) <> ''),

    CONSTRAINT ck_ai_conversation_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);


CREATE TABLE ai_message
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id   BIGINT       NOT NULL,
    role              VARCHAR(20)  NOT NULL,
    content           TEXT         NOT NULL,
    model_name        VARCHAR(100),
    prompt_tokens     INTEGER,
    completion_tokens INTEGER,
    metadata          JSONB        NOT NULL DEFAULT '{}'::JSONB,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_ai_message_conversation
        FOREIGN KEY (conversation_id)
            REFERENCES ai_conversation (id)
            ON DELETE CASCADE,

    CONSTRAINT ck_ai_message_role
        CHECK (role IN ('SYSTEM', 'USER', 'ASSISTANT')),

    CONSTRAINT ck_ai_message_content
        CHECK (BTRIM(content) <> ''),

    CONSTRAINT ck_ai_message_prompt_tokens
        CHECK (prompt_tokens IS NULL OR prompt_tokens >= 0),

    CONSTRAINT ck_ai_message_completion_tokens
        CHECK (completion_tokens IS NULL OR completion_tokens >= 0)
);


CREATE TABLE prompt_template
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 VARCHAR(80) NOT NULL,
    version              INTEGER     NOT NULL,
    system_prompt        TEXT        NOT NULL,
    user_prompt_template TEXT        NOT NULL,
    response_schema      JSONB,
    description          VARCHAR(500),
    active               BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_prompt_template_version
        UNIQUE (code, version),

    CONSTRAINT ck_prompt_template_code
        CHECK (BTRIM(code) <> ''),

    CONSTRAINT ck_prompt_template_version
        CHECK (version > 0),

    CONSTRAINT ck_prompt_template_system
        CHECK (BTRIM(system_prompt) <> ''),

    CONSTRAINT ck_prompt_template_user
        CHECK (BTRIM(user_prompt_template) <> '')
);

CREATE UNIQUE INDEX uk_prompt_template_active
    ON prompt_template (code)
    WHERE active = TRUE;


CREATE INDEX idx_record_batch_user_created
    ON record_batch (user_id, created_at DESC);

CREATE INDEX idx_record_batch_user_status
    ON record_batch (user_id, status);

CREATE INDEX idx_expense_user_time
    ON expense_record (user_id, occurred_at DESC);

CREATE INDEX idx_expense_user_category_time
    ON expense_record (user_id, category_id, occurred_at DESC);

CREATE INDEX idx_expense_batch
    ON expense_record (batch_id);

CREATE INDEX idx_expense_user_anomaly
    ON expense_record (user_id, anomaly_level, occurred_at DESC);

CREATE INDEX idx_budget_user_month
    ON budget_plan (user_id, budget_month);

CREATE INDEX idx_price_rule_keyword
    ON price_reference_rule (normalized_keyword, enabled);

CREATE INDEX idx_prediction_user_month
    ON monthly_prediction (user_id, target_month, generated_at DESC);

CREATE INDEX idx_saving_advice_user_month
    ON saving_advice (user_id, target_month, created_at DESC);

CREATE INDEX idx_conversation_user_updated
    ON ai_conversation (user_id, updated_at DESC);

CREATE INDEX idx_message_conversation_created
    ON ai_message (conversation_id, created_at, id);


CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
AS
$$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER trg_app_user_updated_at
    BEFORE UPDATE ON app_user
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_user_preference_updated_at
    BEFORE UPDATE ON user_preference
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_category_updated_at
    BEFORE UPDATE ON category
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_record_batch_updated_at
    BEFORE UPDATE ON record_batch
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_expense_record_updated_at
    BEFORE UPDATE ON expense_record
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_budget_plan_updated_at
    BEFORE UPDATE ON budget_plan
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_price_rule_updated_at
    BEFORE UPDATE ON price_reference_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_saving_advice_updated_at
    BEFORE UPDATE ON saving_advice
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_ai_conversation_updated_at
    BEFORE UPDATE ON ai_conversation
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_prompt_template_updated_at
    BEFORE UPDATE ON prompt_template
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();